### PR TITLE
Let's add support of postgres search

### PR DESCRIPTION
**Pull request by savelmtr**
This PR adds support of postgres search to django-machina.

Now you can  set on the postgres search just by usung these varyables in settings:

```
MACHINA_SEARCH_ENGINE = 'postgres' #(as default it's haystack)

MACHINA_SEARCH_LANGUAGE = '<your language, default it's english>' #language must be written  only lower case
```

After that (NOT BEFORE!) do `makemigrations` and `migrate`.
If you still made a mistake and migrate before the setting these variables, you may do this:
```
python manage.py dbshell

>use <database_name>;
> select * from django_migrations where app='forum_conversation';
```

You will see the output with ids next to all migrations. Look at the migration named '0012_prepare_postgres_search'. Pick up its ID. Than

```
> delete from django_migrations where id=<ID of the migration>;
```
So, after that migrate.

If you've already got a forum on django-machina, you just can install this upgrade, set `MACHINA_SEARCH_ENGINE= 'postgres'` and makemigrations and migrate. The search will work.

You can check how it already runs on my forum: [alterhist.ru](https://alterhist.ru).

### CODE REVIEW

**Comment by ellmetha** [comment]
@savelmtr I think I would prefer not having to support both haystack and a new way of doing searches. If I were to change how search is done in django-machina, I would replace Haystack completely. 😉

**Comment by savelmtr** [comment]
@ellmetha, ok, may be you're right. Actually, haystack is quite useless... I'll rebuild this search.

**Comment by rainulf** [comment]
@savelmtr This is a great change! Thank you for this.

Note that we may need to add to the doc that `btree_gin` PostgreSQL extension needs to be enabled. I'd actually prefer to further simplifying this to `__icontains` thereby no migration required, but that can be added as an option with this change.

@ellmetha I partially agree with you into dropping haystack (satisfies #178). But I quite like @savelmtr implementation in a way that it opens possibility to customisations and other search engines (such as Elasticsearch, which would be my preference) . Although it's up to your discretion ;)

**Comment by savelmtr** [comment]
Okey, people, I've dropped dependency of haystack. Now we only can search within forums only by icontains or postres full-text search. 
Please, @ellmetha, might you be so kind to help me with tests? I just don't know, how to start right (never done such things before)/

**Comment by savelmtr** [comment]
@ellmetha, I think the commit with renewal of the search is probably ready to merge. Even tests are working. I've not touched files with package settings like poetry.lock etc. But, I think, if you like this implementation of search, we should drop haystack from everywhere. Also we need to append a pair of words about specific of this search into the docs.

**Comment by savelmtr** [comment]
@rainulf, I've finally dropped the haystack search because it supports only deprecated versions of the Elasticsearch and also, for example, Whoosh (abandoned project). Now for simple implementations `icontains` works out-of-the-box and also good and even faster than all these side search machines. Also we could implement the powerful full-text search by Postgres. I hope, this dropping of haystack won't be a big loss for developers, who will choose this forum engine.

**Comment by savelmtr** [comment]
@ellmetha, is something wrong with this PR?

**Comment by savelmtr** [comment]
@ellmetha, you may be right. So, you propose me to make a standalone package for django-machina instead of appending this functional into the main package? Ok, one time I'll perform it.

**Comment by ellmetha** [comment]
Closing this PR. Going further with this would either involve (i) creating a new package for django-machina or (ii) adding support for Postgres search to Haystack (which seems like the best solution IMHO).

**Comment by mslinn** [comment]
I wrote a [blog post about django-haystack](https://www.mslinn.com/blog/2021/02/14/django-fulltext-search.html) and django-oscar which seems apropos for this PR. 

I think that Django would be best served if someone used [django.contrib.postgres.search](https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/search) to add PostgreSQL support to Haystack.

**Comment by savelmtr** [comment]
> Closing this PR. Going further with this would either involve (i) creating a new package for django-machina or (ii) adding support for Postgres search to Haystack (which seems like the best solution IMHO).

Got some troubles while moving code of postgres-search to standalone package. It would be very useful if you could give some tips about what I've done  in wrong way.

https://github.com/ellmetha/django-machina/issues/253

**Comment by savelmtr** [comment]
Ok, here you can check my solution of this problem packed in a module: https://github.com/savelmtr/django-machina-search

**Pull request closed without merging**
