### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by synw**

### CODE REVIEW

**Comment by ellmetha** [comment]
Hi!

Thanks for this PR. As stated in the documentation (https://django-machina.readthedocs.org/en/stable/contributing.html#contributing-translations), the project uses Transifex (https://www.transifex.com/projects/p/django-machina/) to manage its translations.
Could you provide these translations using Transifex ? :)

**Comment by synw** [comment]
I can't manage to do it in Transifex: when I click "Join Team" the french language is not available :/

It asks me to "perform a request language action before joining project translation"

**Comment by ellmetha** [comment]
Hi, I accepted your Transifex join request. ;)

**Comment by synw** [comment]
Ok I will use Transifex

**Pull request closed without merging**
