### PR TITLE
Allow get_class from apps.AppConfig

### PR DESCRIPTION
**Pull request by BoPeng**
https://github.com/ellmetha/django-machina/issues/229 
https://github.com/ellmetha/django-machina/issues/287

Current, `get_class` does not support apps defined in `INSTALLED_APPS` as

```
INSTALLED_APPS = [
    ...
    "machina.forum_tracking.apps.ForumTrackingAppConfig",
    ...
]
```

This does not conform to django conventions and makes deriving from `machina`-defined `AppConfig` more difficult (see #287 for details).

This PR parses `app` and handles the `apps` case for `get_class`.

### CODE REVIEW

**Comment by BoPeng** [comment]
Tests for python 3.6 should be removed, I guess.

image

**Comment by BoPeng** [comment]
@ellmetha I think this PR is clean enough to be merged.

**Review by ellmetha — COMMENTED** [review]
LGTM! 👍  Failing tests are unrelated and where already fixed in `main`.

Can you just add one unit test for this in the [associated test suite](https://github.com/ellmetha/django-machina/blob/main/tests/unit/core/test_loading.py)? 🙏 Then I'll happily merge the change and release a patch version.

**Comment by BoPeng** [comment]
Test added.

**Review by ellmetha — APPROVED** [review]

**Pull request merged**
